platform :ios, '8.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

target 'DkyAppHD' do

pod 'AFNetworking'
pod 'SDWebImage'

pod 'Masonry'
pod 'UITableView+FDTemplateLayoutCell'
pod 'IQKeyboardManager'

pod 'VTMagic'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'
pod 'MJRefresh'
pod 'iCarousel'
pod 'RMUniversalAlert'

pod 'MJExtension'
pod 'YYCategories'
pod 'YYCache'
pod 'SAMKeychain'


pod 'QMUIKit'
end
